<template>
  <div>
    <div class="page-head"><div><h2 class="page-title">预警提示</h2><p class="page-subtitle">团雾检测预警记录管理</p></div><select v-model="sourceType" class="select filter" @change="load"><option value="">全部来源</option><option value="image">图片</option><option value="video">视频</option><option value="camera">摄像头</option></select></div>
    <section class="warning-summary"><div><span>预警总数</span><strong>{{ items.length }}</strong></div><div><span>重度以上</span><strong>{{ severeCount }}</strong></div><div><span>最新来源</span><strong>{{ latestSource }}</strong></div></section>
    <div class="table-wrap"><table><thead><tr><th>地段</th><th>来源</th><th>团雾等级</th><th>能见度</th><th>限速</th><th>目标数</th><th>时间</th><th v-if="user.role==='admin'">用户</th><th>截图</th><th>操作</th></tr></thead>
    <tbody><tr v-for="item in items" :key="item.id"><td class="road-cell">{{ item.road_section }}</td><td><span class="tag">{{ typeName(item.source_type) }}</span></td><td><span :class="['level-badge',levelClass(item.fog_level)]">{{ item.fog_level }}</span></td><td>{{ item.visibility_level }}</td><td>{{ item.speed_limit }}</td><td>{{ item.detect_count }}</td><td>{{ item.created_at }}</td><td v-if="user.role==='admin'">{{ item.full_name||item.username }}</td><td><a v-if="item.snapshot_url" class="link" :href="item.snapshot_url" target="_blank">查看</a><span v-else class="muted">-</span></td><td><button class="button danger small" @click="remove(item.id)">删除</button></td></tr>
    <tr v-if="!items.length"><td :colspan="user.role==='admin'?10:9" class="empty-cell">暂无预警记录</td></tr></tbody></table></div>
    <p class="error-text">{{ error }}</p>
  </div>
</template>
<script>export default {name:"WarningList",props:{user:{type:Object,required:true}},data(){return{sourceType:"",items:[],error:""}},computed:{severeCount(){return this.items.filter(i=>/重度|特重/.test(i.fog_level)).length},latestSource(){return this.items.length?this.typeName(this.items[0].source_type):"-"}},created(){this.load()},methods:{async load(){this.error="";try{const s=this.sourceType?"?source_type="+this.sourceType:"";const d=await this.$api.get("/api/warnings"+s);this.items=d.items||[]}catch(e){this.error=e.message}},async remove(id){this.error="";try{await this.$api.delete("/api/warnings/"+id);this.items=this.items.filter(i=>i.id!==id)}catch(e){this.error=e.message}},typeName(t){return{image:"图片",video:"视频",camera:"摄像头"}[t]||t},levelClass(l){if(/特重/.test(l))return"critical";if(/重度/.test(l))return"high";if(/中度/.test(l))return"medium";return"low"}}};</script>
<style scoped>.filter{width:160px}.warning-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}.warning-summary div{border:1px solid #e2e8f0;border-radius:10px;background:#fff;padding:18px;box-shadow:0 4px 16px rgba(15,23,42,.06)}.warning-summary span{display:block;color:#64748b;font-size:12px;margin-bottom:6px;text-transform:uppercase;letter-spacing:.5px}.warning-summary strong{font-size:26px;color:#1e293b}.road-cell{min-width:180px;font-weight:700}.level-badge{display:inline-flex;align-items:center;min-height:26px;border-radius:999px;padding:0 10px;font-size:12px;font-weight:800}.level-badge.low{color:#166534;background:#dcfce7}.level-badge.medium{color:#854d0e;background:#fef3c7}.level-badge.high{color:#9a3412;background:#ffedd5}.level-badge.critical{color:#991b1b;background:#fee2e2}.link{color:#0f766e;font-weight:700}.muted{color:#94a3b8}.empty-cell{text-align:center;color:#94a3b8;padding:40px}@media(max-width:760px){.warning-summary{grid-template-columns:1fr}}</style>